Fix validation in extractRevenue method in plugins_appsflye
segmentio/analytics_flutter pull request #41
Opened 2023-11-20 18:16 UTC by edsonjab

Fix issue #36

2023-11-27 20:48 UTC, QoLTech requested changes

2023-11-27 20:48 UTC, QoLTech commented on packages/plugins/plugin_appsflyer/lib/utils.dart
> +  if (nul == properties[key] ) {
I would do `properties[key] == null`

2023-11-28 18:31 UTC, QoLTech approved these changes

2023-12-05 19:05 UTC, oscb approved these changes

2023-12-05 19:05 UTC, merged