Remove validation to identify once and track app is installed
segmentio/analytics_flutter pull request #45
Opened 2023-12-13 16:41 UTC by edsonjab

Fix #42

2023-12-13 18:44 UTC, oscb requested changes

2023-12-13 18:44 UTC, oscb commented on packages/core/lib/analytics.dart
> +    if (context.app.version != previousContext.app.version) {
This won't really fix the `Application Installed` event not being triggered as this is the only place where this is tracked.

I think the solution should either be:
- Change the initialization of context so that it is `null` at this point. Then we can call the native function to fill the values.
- Do a different check at this point to see if the app is just installed. f.e. instead of checking context we can persist a flag.

2023-12-13 18:48 UTC, oscb commented on packages/core/lib/analytics.dart
> +    if (context.app.version != previousContext.app.version) {
My only concern with changing the initialization of Context would be concurrency issues. Specially with plugins like IDFA, AdvertisingID. Not 100% sure if  any plugin might be expecting context to be populated from the get-go and hence why it is initialized right away.

The second solution might be simpler and more sound.

2023-12-19 19:27 UTC, chrisradek approved these changes

2023-12-19 19:27 UTC, oscb approved these changes

2023-12-19 19:27 UTC, oscb approved these changes

2023-12-19 19:28 UTC, merged