Add validation to get anonymousId from storage or cookies on web
segmentio/analytics_flutter pull request #50
Opened 2023-12-26 23:45 UTC by edsonjab

Fix issue #46

2023-12-28 00:08 UTC, QoLTech commented
Woohoo!

2023-12-28 00:10 UTC, QoLTech requested changes

2023-12-28 00:10 UTC, QoLTech commented on packages/core/lib/utils/store/web.dart
> +    if(data != null && fileKey  == "userInfo") {
data would only be not-null here if this is a subsequent visit to the app. We actually want this even on the first visit as well. In fact, that's the most important part of doing this.

2023-12-28 00:12 UTC, QoLTech commented on packages/core/lib/utils/store/web.dart
> +    if(data != null && fileKey  == "userInfo") {
If we actually checked data == null, that would get us what we wanted. Since they should never have this file in local storage if they went to our marketing site and then to our web app.

2023-12-28 00:50 UTC, edsonjab commented on packages/core/lib/utils/store/web.dart
> +    if(data != null && fileKey  == "userInfo") {
I don't understand, what is the scenario that you need?

> If we actually checked data == null, that would get us what we wanted. Since they should never have this file in local storage if they went to our marketing site and then to our web app.

2023-12-28 20:22 UTC, QoLTech commented on packages/core/lib/utils/store/web.dart
> +    if(data != null && fileKey  == "userInfo") {
If this is the first visit to the website, there would be no 'userInfo' file, so data would be null. In this case, we wouldn't check the local storage or cookies for the 'ajs_anonymous_id'. We _do_ want to check for the 'ajs_anonymous_id' even if the 'userInfo' file was null.

2023-12-28 20:24 UTC, QoLTech commented on packages/core/lib/utils/store/web.dart
> +    if(data != null && fileKey  == "userInfo") {
Our users flow from our marketing website (analytics.js which writes 'ajs_anonymous_id' to localstorage and cookies) to our Flutter Web app which uses this library. For these users, we want to be able to persist that 'ajs_anonymous_id', which your implementation would not do since you do not check those since `data != null`.

2024-01-03 15:53 UTC, QoLTech approved these changes

2024-01-08 20:18 UTC, oscb requested changes
Good job! This looks good, one final thing, this feels like a behavior that should be documented. Can you add this into the readme? We can add a new section under `Usage` for `Platform Specific` where for web it mentions that it will use `AJS` `anonymousId` cookie/localStorage if present

2024-01-08 20:18 UTC, oscb commented on packages/core/lib/utils/store/web.dart
> +
This is great! Can we put this though in another method to make it clear this is an specific behavior for compatibility with AJS. Let's call it something like `getUserInfoFromAJS`.

Another idea:
It might be tricky to keep these AnonymousID in sync. I think for a starting point it is good enough to have it go one-way (AJS -> Flutter) as it is right now, but might be good to enable a flag in this storage object so that it can switch which storage to prioritize. Food for thought, doesn't have to be done right now.

Another more actionable idea: right now this always patches up the `userInfo.anonymousId` but in reality this will likely only be required once: when going from the marketing site (AJS) to the web app (Flutter). You could have the storage check if there's any `anonymousId` on the cookies/localstorage and patch the `userInfo` object at construction time and then resume normal flow

2024-01-08 20:18 UTC, oscb commented on packages/core/lib/utils/store/web.dart
> +
Actually the last idea might be required, as the way it works right now prevents `reset()` from recreating an anonymousId (it is always overwritten by the AJS one).

2024-01-08 21:28 UTC, QoLTech commented on packages/core/lib/utils/store/web.dart
> +
@oscb Are you suggesting that we only check for anonymousId one time when we create the local storage files for this library? That way after a call to reset(), it doesn't pull it again? That seems like it would be fine for my use case.

Is there a similar reset() function in the analytics.js library? Does it makes sense to have this be two-way?

Should a reset() call from analytics.js clear the data this library uses? And should a reset() call in this library clear the analytics.js ajs_anonymous_id cookie/local storage file? That would also solve the 'stickiness' problem.

2024-01-10 01:16 UTC, QoLTech requested changes

2024-01-10 01:16 UTC, QoLTech commented on packages/core/lib/utils/store/web.dart
> +      anonymousId = getUserInfroFromAJS(data);
getUserInfroFromAJS -> getUserInfoFromAJS

2024-01-10 01:16 UTC, QoLTech commented on packages/core/lib/utils/store/web.dart
> +      anonymousId = getUserInfroFromAJS(data);
Or better yet, maybe getAnonymousIdFromAnalytic, getAnonymousIdFromStorage, or getExistingAnonymousId? Or something like that?

2024-01-24 18:54 UTC, oscb approved these changes
Great work!!

2024-01-24 18:54 UTC, oscb commented on README.md
> +The code will use AJS anonymousId from cookies or localStorage if present.
```suggestion
`analytics_flutter` on web will check for `Analytics.JS` userInfo cookies/localStorage and reuse the `anonymousId` data.

LocalStorage recovery only works when running in the same domain/subdomain.
```

Minor rewording to be more explicit of the limitations.

2024-01-24 19:49 UTC, QoLTech approved these changes

2024-01-26 22:45 UTC, merged