Add plugin to add token on context
segmentio/analytics_flutter pull request #73
Opened 2024-05-01 05:27 UTC by edsonjab

Fix issue #71

2024-05-15 16:52 UTC, MichaelGHSeg approved these changes

2024-05-15 19:27 UTC, MichaelGHSeg approved these changes

2024-05-15 19:39 UTC, MichaelGHSeg requested changes
Oops, that caused more test failures

2024-05-29 12:14 UTC, MichaelGHSeg commented on packages/core/test/analytics_test.dart
> +import 'package:analytics/analytics.dart';
This seems to have cause a lot of errors with missing functions etc.

2024-05-29 15:27 UTC, nd4p90x commented on packages/core/test/analytics_test.dart
> +import 'package:analytics/analytics.dart';
@edsonjab

2024-05-30 00:14 UTC, edsonjab commented on packages/core/test/analytics_test.dart
> +import 'package:analytics/analytics.dart';
Hi @MichaelGHSeg I made double check on local must to be works now with the new commit.

2024-06-03 17:44 UTC, MichaelGHSeg approved these changes

2024-06-03 17:45 UTC, merged